### 1. Hello World!를 출력해 보세요.

In [ ]:
'Hello World!'

## 사칙연산
### 2. 더하기 1 + 1 을 아래의 셀에 입력 후 실행해 보세요.

In [ ]:
1 + 1

### 3. 빼기 7 - 3 을 아래의 셀에 입력 후 실행해 보세요.

In [ ]:
7 - 3

### 4. 곱하기 3 * 4 를 아래의 셀에 입력 후 실행해 보세요.

In [ ]:
3 * 4

### 5. 나누기 3/2 를 아래의 셀에 입력 후 실행해 보세요.

In [ ]:
3/2

## 변수
### 6. 변수할당하기 "Python"이라는 문자를 p라는 변수에 할당해 주세요.
* 참고: https://dojang.io/mod/page/view.php?id=2176

In [ ]:
p = 'Python'

### 7. 위에 있는 링크를 참고해서 p 라는 변수에 담겨있는 값을 type을 통해 출력해 주세요.

In [ ]:
type(p)

### 8. p라는 변수에 담겨있는 문자열을 소문자로 변경해 주세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2299 (24.1.5  소문자를 대문자로 바꾸기)

In [ ]:
p.lower()

### 9. p라는 변수에 담겨있는 문자열을 대문자로 변경해 주세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2299 (24.1.6  대문자를 소문자로 바꾸기)

In [ ]:
p.upper()

### 10. number 라는 변수에 1234 를 할당해 주세요.
* 참고: https://dojang.io/mod/page/view.php?id=2176

In [ ]:
number = '1234'

### 11. number 라는 변수에 담겨있는 값을 type을 통해 출력해 주세요.
* 참고: https://dojang.io/mod/page/view.php?id=2176

In [ ]:
type(number)

## 비교연산

### 12. 1 + 2 는 3 과 같습니다.  1 + 2 가 3과 같음을 표현해 보세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2191

In [ ]:
1 + 2 == 3

### 13. 1 + 2 는 4와 다릅니다. 위 문제의 링크를 참고해서 1 + 2 가 4와 같지 않음을 표현해 보세요.

In [ ]:
1 + 2 == 4

### 14. 2 + 3 은 4보다 크다는 것을 표현해 보세요. 결과값이 True가 찍히도록 구현합니다.

In [ ]:
2 + 3 > 4

### 15. 2 + 3 은 6보다 작다는 것을 표현해 보세요. 결과값이 True가 찍히도록 구현합니다.

In [ ]:
2 + 3 < 6

## 문자열
### 16. 다음은 서울에 있는 구를 문자열 형태로 만들어 gu 라는 변수에 담아놓았습니다.
* gu라는 변수가 선언되게 아래의 셀을 실행해 주세요.

In [ ]:
gu = ['강남구 강동구 강북구 강서구 관악구 광진구 구로구 금천구 노원구 도봉구 동대문구 동작구 마포구 서대문구 서초구 성동구 성북구 송파구 양천구 영등포구 용산구 은평구 종로구 중구 중랑구']

### 17. 다음 링크의 split() 을 활용해 gu 라는 변수에 담겨있는 값을 리스트 형태를 변경해 주세요. 그리고 gu_list 라는 변수에 결과 값을 담아주세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2299 (24.1.3  문자열 분리하기)

In [ ]:
gu_list = '강남구 강동구 강북구 강서구 관악구 광진구 구로구 금천구 노원구 도봉구 동대문구 동작구 마포구 서대문구 서초구 성동구 성북구 송파구 양천구 영등포구 용산구 은평구 종로구 중구 중랑구'.split()
type(gu_list)

### 18. len 을 활용하여 gu 라는 변수에 담겨져 있는 문자열의 수를 세어보세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2206

In [ ]:
len(gu)

### 19. join 을 사용해서 gu_list 변수 안에 담겨져 있는 값을 공백(스페이스)으로 연결되도록 해보세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2299 (24.1.4  구분자 문자열과 문자열 리스트 연결하기)

In [ ]:
' '.join(gu_list)

### 20. 반복문(for)을 사용하여 구를 순서대로 출력해 주세요.
* 아래 for문이 오류 없이 돌아가도록 변경해 주세요.

In [ ]:
for g in gu_list:
    print(g)

### 21. "2020년 02월"이라는 문자열에서 split 과 인덱싱을 사용해서 월을 분리해 주세요. 02를 출력합니다.

In [ ]:
a = "2020년 02월"
a = a.split()[1]
a = list(a)
''.join(a)[0:2]

### 22. 다음의 리스트에서 스타벅스일때는 "스타벅스 green" 을 이디야 일때는 "이디야 blue"를 출력하도록 하는 코드입니다. 제대로 동작하도록 수정해 보세요.

In [ ]:
coffee = ["스타벅스", "이디야"]

for c in coffee:
    if c == "스타벅스":
        print(c, "green")
    elif c=="이디야":
        print(c, "blue")

### 23. 아래의 for 문이 5번 print 문을 출력하도록 수정해 보세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2241

In [ ]:
for i in range(5):
    print(i)

### 24. % 연산을 하면 나머지를 구할 수 있습니다. 아래의 코드에서 홀수가 출력되도록 코드를 수정해 보세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2227

In [ ]:
number = 11
if number % 2 == 0 :
    print("짝수")
else:
    print("홀수")

### 25. 슬라이스를 사용하면 문자열이나 리스트를 원소의 번호로 나눌 수 있습니다. 아래의 전화번호에서 010 국번만 출력하도록 슬라이싱을 해보세요.
* 참고 : https://dojang.io/mod/page/view.php?id=2208

In [ ]:
mobile = "82-010-9876-4321"
b = mobile.split('-')
b[1]